study:
  study_name: cifar10_colouriser_lencoder_lr_pow2_optuna
  direction: minimize
  storage: postgresql+psycopg2://mluser:mlpass@localhost:5432/optuna
  load_if_exists: true
  sampler:
    class_path: optuna.samplers.TPESampler
    init_args:
      seed: 22
      multivariate: true

objective:
  metric: val_lpips
  enable_pruning: true

output:
  best_config_path: outputs/cifar10_colouriser_lencoder_lr_pow2_optuna_best.yaml

n_trials: 10

search_space:
  model:
    init_args:
      lr:
        type: float
        low: 0.00001
        high: 0.001
        log: true
  data:
    init_args:
      batch_size:
        type: categorical
        choices: [16, 32, 64, 128, 256]
